runtime: python39  # Using Python 3.9 (GAE standard environment supports up to Python 3.9)

entrypoint: streamlit run homepage.py --server.port=$PORT --server.address=0.0.0.0

instance_class: F2  # Adjust based on your needs

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  STREAMLIT_ENV: "production"

